Repository developer-student-club-thapar/PermissionApp, pull requests merged in 2020-05, with the labels that each got.

#27 Configured git hooks
  .markdownlint.json
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .prettierignore
  .prettierrc.js
Labels: enhancement

#29 Major linitng upgrade
  .markdownlint.json
  .pre-commit-config.yaml
  .prettierrc.js
  CONTRIBUTION.md
  README.md
  backend/app.js
  backend/controllers/permi-controllers.js
  backend/controllers/users-controllers.js
  backend/middleware/check-auth.js
  backend/models/EarlyLeavepermi-model.js
  backend/models/LateEntrypermi-model.js
  backend/models/Librarypermi-model.js
  backend/models/Societypermi-model.js
  backend/models/http-error.js
  backend/models/user-model.js
  backend/routes/permi-routes.js
  backend/routes/users-routes.js
  frontend/App.js
  frontend/app.json
  frontend/babel.config.js
  frontend/components/Button.js
  frontend/components/ButtonFilled.js
  frontend/components/LoginOptions.js
  frontend/components/Post.js
  frontend/components/ScrollViewEntry.js
  frontend/components/Validator.js
  frontend/components/context/auth-context.js
  frontend/components/navigation/DrawerContentComponents.js
  frontend/components/navigation/Header.js
  frontend/components/navigation/Menu.js
  frontend/components/navigation/NavCenterComponent.js
  frontend/components/navigation/Navigation.js
  frontend/components/ui/Date.js
  frontend/components/ui/Input.js
  frontend/components/ui/Time.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/Caretaker.js
  frontend/screens/EarlyLeave.js
  frontend/screens/Hidden.js
  frontend/screens/Home.js
  frontend/screens/LateEntry.js
  frontend/screens/Library.js
  frontend/screens/LogIn.js
  frontend/screens/PreviousWarden.js
  frontend/screens/Society.js
  frontend/screens/Status.js
  frontend/screens/Warden.js
Labels: enhancement, help wanted

#37 Rename CONTRIBUTION.md to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#36 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation
